language: java

# Travis doesn't (yet) support OpenJDK 8
jdk:
  - oraclejdk8

# Replace Travis's default Maven installation step with a no-op.
# This avoids redundantly pre-running 'mvn install -DskipTests' every time.
install: true
# Replace Travis's default build step.
# Run all Maven phases at once up through verify, install, and deploy.
script: |
  # only (attempt to) deploy non-pull request commits to the master branch or on tags
  if [[ "$TRAVIS_PULL_REQUEST" = false ]] && [[ "$TRAVIS_BRANCH" = master || ! -z "$TRAVIS_TAG" ]]; then
    mvn clean deploy
  else
    # otherwise, just run test suite
    mvn clean verify
  fi


# If sudo is disabled, CI runs on container based infrastructure (allows caching &c.)
sudo: false

# Retain the local Maven repository to speed up builds.
cache:
  directories:
    - "$HOME/.m2/repository"

# Notify us of the build status on the Slack channel
notifications:
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc

# Push results to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
