language: java
jdk:
  - oraclejdk8
install: true
sudo: false
cache:
  directories:
    - "$HOME/.m2/repository"
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
script:
  - mvn package
notifications:
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc
addons:
  artifacts:
    path: $(ls target/dt-*.jar)
    key:
      secure: 0jfJjYgNrIXZylc3kSpUtdt3EFcVdElzc769gGlAKwZ4WcaXlezjQQmdwZRGQj5nYjg4xKGyCLSfJC4UHSFS2c2O8gssLAZ9oySmGP0GKieq8rWXoXuWSVtP4U5jOrBgGuPuLzJu9yeAdPUQAvCJtFfw5bPj2CnliznYPMdUIkyTYW/ehWUNnKirL0cabjMMxGzq33FMTzJ0eHWM/XPXPp0Nnh1YLXkavXSyR7AsyPPXWx2r2rmERbWxu4C4JGB5eYEdXmJ2OyHV14AJuOdIyGHCb56ttUU85vxSwbZooPqM7w4MNbKr7hgaURAK4nhsQbd9LgRrWz9RmWpekTdLTvB3h+8ZivcoG83kQZD2jWDu4elTp/zg0V6Z2SDoS3mvQ/N9E/arzS4aMgeQFopvj1QRAv+xR3dMh9rD9agFesG2N2hpZ31iWbb9AlpNAldKzV2fz/yirSF+j374k3RKlkLMFvzVriBcaK4ehYLtfs0gi89xlo8/+V0vLSHDxSIKjg1kFiO2H1f7I+G21vXNYz2L5bSSgb4R0Tc3of5f/TTyTc9nkSNEg3VklwJEE38gutkJf/Ue7Uy9DxHUGMmpNTkBh/yymqX0EoxCtXeZi+Z9FcECP4BBLqIfmBIXs56PSCegxmmgX+Sbdsl2nLJwT4L0sciLEfvqJp+I4xUIu+g=
    secret:
      secure: iubobdkbB0sJGFheo5vWGYwuKt/nlCvgKo4eb+sp0j2J70KvcOsk+uUidxbi7p7XG6AhmX2G0h5Sw5IXTmYfs32ZEYsxgNqxuht7vNvw7lrlFAhIq+P5uho/1VWTx5ObbUnNVkuesqaVFKWcfN83f8f5YYD8Q3C0YXLufIhRATkjTPhaJwmzpyQZC4G0Y2zz+o1cAP5InC2HoiuVIoGI5iUy4KU7XHkZTmiQelm5eQgsxnu7Cj/h77sLUicy7Q3VpriL7Xrwr8CWVvi0KjHOWgBwlF1CqIFnIlt7wpWqHLKh8cKSrMgb07NtZpvjy/giTZxBM4lfm3Pixh+Wqwnjm3WT8dgWMEju/PEmVzoRb37BHGj7RPOf0OOcTOZGEmyfwpQQ4dN2fJPwuSLAaEnOxjrZ//uNJ3QsSj7LrPNGUK4NcQBGMSGzzY2yj6vzllZtQkReAtizUbx7MrriCYPg3slMD/JRtVugNfbH6ceS9EhHczjbRTXa28yOk2TO7H7whUfn5JT1N+NM/Oo0abzEsU0CDUT+37JhPtoZql+dc2cj3YyVigSZFHA/5ICbnZdjqvjrNjO3DyVI1TcIYIArgfyd+oUWbGUZyCFMT3+wa7kAP4k81D8tmCiWJy4gcK3RsXxooL+f8EZSqFxpih77Kw4cAOJbpZ5+xImeBMRMbe8=
    bucket: datatools-builds
